version: "3.8"

services:
  noise01:
    build: .
    container_name: noise01

  noise02:
    build: .
    container_name: noise02

  fluentd:
    image: ihuntenator/fluentd-hec:1.9
    container_name: fluentd
    hostname: clddfluentd01
    portis:
      - "24224:24224"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:Z
      - /opt/fluentd-hec/fluentd:/fluentd/:Z
    environment:
      TZ: "Pacific/Auckland"
    command: >
      sh -c "fluentd -c /fluentd/etc/fluentd.conf"
