version: "3.8"

services:
  noise01:
    build: .

  noise02:
    build: .

  fluentd:
    image: ihuntenator/fluentd-hec:1.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:Z
    environment:
      TZ: "Pacific/Auckland"
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&
      exec fluentd -c /fluentd/etc/fluentd.conf"
#    command: --label=com.centurylinklabs.watchtower.enable=true

#  watchtower:
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /root/.docker/config.json:/config.json
#    command: --interval 30 --enable-label
